trailingComma: "all"
quoteProps: "consistent"
plugins:
  [
    "prettier-plugin-sql",
    "prettier-plugin-embed",
    "prettier-plugin-organize-imports",
    "prettier-plugin-css-order",
    "prettier-plugin-packagejson",
  ]
organizeImportsSkipDestructiveCodeActions: true
# https://github.com/un-ts/prettier/tree/master/packages/sql#parser-options
language: "postgresql"
database: "postgresql"
keywordCase: "upper"
# https://github.com/Sec-ant/prettier-plugin-embed?tab=readme-ov-file#sql
embeddedSqlParser: "postgresql"
# https://github.com/Siilwyn/css-declaration-sorter/?tab=readme-ov-file#built-in-sorting-orders
cssDeclarationSorterOrder: "frakto"
