import { chromium } from "playwright";
const browser = await chromium.launch();
const p = await browser.newPage();
const errs = [];
p.on("pageerror", (e) => errs.push(String(e).slice(0, 200)));
await p.goto("http://127.0.0.1:3456/packages/frontend/navi/src/control/demos/10_duration_preset_demo.html", { waitUntil: "load", timeout: 90000 });
await p.waitForTimeout(4000);
console.log("errors:", errs.length ? errs.slice(0, 2) : "none");
const item = p.locator('[commandfor="custom_duration_picker3"]').first();
console.log("label:", await item.evaluate((el) => el.closest("li").textContent.trim().slice(0, 18)));
await item.click({ force: true });
await p.waitForTimeout(900);
const dlg = p.locator("#custom_duration_picker3_picker_popup");
console.log("fields on open:", await dlg.evaluate((el) => [...el.querySelectorAll("input")].map((i) => `${i.name || "?"}=${i.value}`)));
await dlg.locator('input[name="hour"]').fill("3");
await dlg.locator('input[name="hour"]').press("Tab");
await p.waitForTimeout(700);
console.log("after 3h -> url:", await p.evaluate(() => location.search));
console.log("label:", await item.evaluate((el) => el.closest("li").textContent.trim().slice(0, 18)));
await browser.close();
