await import("./array.test.js");
// await import("./assert_between.test.js");
await import("./assert_not.test.js");
await import("./function.test.js");
await import("./map.test.js");
await import("./max_columns.test.js");
await import("./object.test.js");
await import("./set.test.js");
await import("./string.test.js");
await import("./wrapped_value.test.js");
