export const renderGeneratedByText = ({
  generatedByLink,
  runLink,
  commitLink,
}) => {
  if (runLink && typeof runLink !== "object") {
    console.warn(
      `runLink ignored because it should be an object with {url, text}, received ${runLink}`,
    );
    runLink = null;
  }

  const parts = [
    `Generated by <a href="${generatedByLink.url}">${generatedByLink.text}</a>`,
    ...(runLink ? [`during <a href="${runLink.url}">${runLink.text}</a>`] : []),
    ...(commitLink
      ? [`on <a href="${commitLink.url}">${commitLink.text}</a>`]
      : []),
  ];

  return `<sub>
  ${parts.join(` `)}
</sub>`;
};
