/*
 * ok on est pas mal
 * on va pouvoir commencer a tester
 */

import {
  fileSystemPathToUrl,
  isFileSystemPath,
  urlToFilename,
  urlToRelativeUrl,
} from "@jsenv/urls";
import { takeFileSnapshot } from "../filesystem_snapshot.js";
import { createCaptureSideEffects } from "./create_capture_side_effects.js";
import { renderSideEffects } from "./render_side_effects.js";

// TODO: write some jsdoc
export const snapshotTests = async (
  fnRegisteringTest,
  snapshotFileUrl,
  {
    testFileUrl, // si on le passe on pourra dire executing X
    // footer genre "this file was generated by [@jsenv/snapshot]() executing [toto.test.js]()"
    generatedBy = true,
  },
) => {
  const testMap = new Map();
  const onlyTestMap = new Map();
  const test = (scenario, fn, options) => {
    testMap.set(scenario, { fn, options, callSite: getTestCallSite() });
  };
  test.ONLY = (scenario, fn, options) => {
    onlyTestMap.set(scenario, { fn, options, callSite: getTestCallSite() });
  };
  fnRegisteringTest({ test });

  const activeTestMap = onlyTestMap.size ? onlyTestMap : testMap;
  const captureSideEffects = createCaptureSideEffects({
    rootDirectoryUrl: testFileUrl ? new URL("./", testFileUrl) : null,
  });
  let markdown = "";
  markdown += `# ${urlToFilename(snapshotFileUrl)}`;
  markdown += "\n\n";
  for (const [scenario, { fn, callSite }] of activeTestMap) {
    markdown += `## ${scenario}`;
    markdown += "\n\n";
    const sideEffects = await captureSideEffects(fn, { callSite });
    const sideEffectsMarkdown = renderSideEffects(sideEffects, {
      sideEffectFileUrl: snapshotFileUrl,
      outDirectoryUrl: new URL(
        `./${asValidFilename(scenario)}/`,
        snapshotFileUrl,
      ),
      generatedBy: false,
      titleLevel: 3,
    });
    markdown += sideEffectsMarkdown;
  }
  const sideEffectFileSnapshot = takeFileSnapshot(snapshotFileUrl);
  if (generatedBy) {
    let generatedByLink = `Generated by [@jsenv/snapshot](https://github.com/jsenv/core/tree/main/packages/independent/snapshot)`;
    if (testFileUrl) {
      const testFileRelativeUrl = urlToRelativeUrl(
        testFileUrl,
        snapshotFileUrl,
      );
      generatedByLink += ` executing [${testFileRelativeUrl}](${testFileRelativeUrl})`;
    }
    markdown += "\n\n";
    markdown += generatedByLink;
  }
  sideEffectFileSnapshot.update(markdown, { mockFluctuatingValues: false });
};

const getTestCallSite = () => {
  const { prepareStackTrace } = Error;
  Error.prepareStackTrace = (error, stack) => {
    Error.prepareStackTrace = prepareStackTrace;
    return stack;
  };
  const { stack } = new Error();
  Error.prepareStackTrace = prepareStackTrace;
  const callerCallsite = stack[2];
  const fileName = callerCallsite.getFileName();
  const testCallSite = {
    url:
      fileName && isFileSystemPath(fileName)
        ? fileSystemPathToUrl(fileName)
        : fileName,
    line: callerCallsite.getLineNumber(),
    column: callerCallsite.getColumnNumber(),
  };
  return testCallSite;
};

// see https://github.com/parshap/node-sanitize-filename/blob/master/index.js
const asValidFilename = (string) => {
  return string
    .trim()
    .toLowerCase()
    .replace(/[ ,.]/g, "_")
    .replace(/["/?<>\\:*|]/g, "");
};
