// we won't internalize @jsenv/url-meta
// so that @jsenv/url-meta does not becomes nodejs specific
// but these functions could be inside this repository
export {
  applyPatternMatching,
  normalizeStructuredMetaMap,
  urlCanContainsMetaMatching,
  urlToMeta,
} from "@jsenv/url-meta"

export { assertAndNormalizeDirectoryUrl } from "./src/assertAndNormalizeDirectoryUrl.js"
export { assertAndNormalizeFileUrl } from "./src/assertAndNormalizeFileUrl.js"
export { assertDirectoryPresence } from "./src/assertDirectoryPresence.js"
export { assertFilePresence } from "./src/assertFilePresence.js"
export { bufferToEtag } from "./src/bufferToEtag.js"
export { collectDirectoryMatchReport } from "./src/collectDirectoryMatchReport.js"
export { collectFiles } from "./src/collectFiles.js"
export { comparePathnames } from "./src/comparePathnames.js"
export { ensureEmptyDirectory } from "./src/ensureEmptyDirectory.js"
export { ensureParentDirectories } from "./src/ensureParentDirectories.js"
export { ensureWindowsDriveLetter } from "./src/ensureWindowsDriveLetter.js"
export { copyEntry } from "./src/copyEntry.js"
export { copyDirectoryContent } from "./src/copyDirectoryContent.js"
export { fileSystemPathToUrl } from "./src/fileSystemPathToUrl.js"
export { fileSystemRootUrl } from "./src/fileSystemRootUrl.js"
export { getRealFileSystemUrlSync } from "./src/getRealFileSystemUrlSync.js"
export { grantPermissionsOnEntry } from "./src/grantPermissionsOnEntry.js"
export { isFileSystemPath } from "./src/isFileSystemPath.js"
export { listFilesMatching } from "./src/listFilesMatching.js"
export { memoize } from "./src/memoize.js"
export { moveDirectoryContent } from "./src/moveDirectoryContent.js"
export { moveEntry } from "./src/moveEntry.js"
export { moveUrl } from "./src/moveUrl.js"
export { readDirectory } from "./src/readDirectory.js"
export { readFile } from "./src/readFile.js"
export { readFileSync } from "./src/readFileSync.js"
export { readEntryModificationTime } from "./src/readEntryModificationTime.js"
export { readEntryPermissions } from "./src/readEntryPermissions.js"
export { readEntryStat } from "./src/readEntryStat.js"
export { readSymbolicLink } from "./src/readSymbolicLink.js"
export { registerDirectoryLifecycle } from "./src/registerDirectoryLifecycle.js"
export { registerFileLifecycle } from "./src/registerFileLifecycle.js"
export { removeEntry } from "./src/removeEntry.js"
export { resolveDirectoryUrl } from "./src/resolveDirectoryUrl.js"
export { resolveUrl } from "./src/resolveUrl.js"
export { testEntryPermissions } from "./src/testEntryPermissions.js"
export { urlIsInsideOf } from "./src/urlIsInsideOf.js"
export { urlToBasename } from "./src/urlToBasename.js"
export { urlToExtension } from "./src/urlToExtension.js"
export { urlToFilename } from "./src/urlToFilename.js"
export { urlToFileSystemPath } from "./src/urlToFileSystemPath.js"
export { urlToOrigin } from "./src/urlToOrigin.js"
export { urlToParentUrl } from "./src/urlToParentUrl.js"
export { urlToPathname } from "./src/urlToPathname.js"
export { urlToRelativeUrl } from "./src/urlToRelativeUrl.js"
export { urlToRessource } from "./src/urlToRessource.js"
export { urlToScheme } from "./src/urlToScheme.js"
export { writeDirectory } from "./src/writeDirectory.js"
export { writeFile } from "./src/writeFile.js"
export { writeFileSync } from "./src/writeFileSync.js"
export { writeEntryModificationTime } from "./src/writeEntryModificationTime.js"
export { writeEntryPermissions } from "./src/writeEntryPermissions.js"
export { writeSymbolicLink } from "./src/writeSymbolicLink.js"
