import { exec as nodeExec } from "node:child_process";

export const exec = (
  command,
  { cwd, input, onLog = () => {}, onErrorLog = () => {} } = {},
) => {
  return new Promise((resolve, reject) => {
    const commandProcess = nodeExec(
      command,
      {
        cwd,
        input,
        stdio: "silent",
      },
      (error, stdout) => {
        if (error) {
          reject(error);
        } else {
          resolve(stdout);
        }
      },
    );

    commandProcess.stdout.on("data", (data) => {
      onLog(data);
    });
    commandProcess.stderr.on("data", (data) => {
      // debug because this output is part of
      // the error message generated by a failing npm publish
      onErrorLog(data);
    });
  });
};
